trigger:
  batch: true
  branches:
    include:
    - master
    - bufix/*
    - feature/*
    - hotfix/*
    - release/*
  paths:
    exclude:
    - README.md

pool:
  name: Azure Pipelines
  vmImage: 'windows-2019'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  buildPlatform: 'x64'
  
steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.4.0'
  inputs:
    versionSpec: '5.4.0'
    checkLatest: true

- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: GitVersion

- script: echo %Action%%BuildVersion%
  displayName: 'Set build version'
  env:
    Action: '##vso[build.updatebuildnumber]'
    BuildVersion: $(GitVersion.NugetVersionV2)

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: 'build/ctre.nuspec;!build/ctre.symbols.nuspec'
    buildProperties: 'VERSION=$(build.buildNumber)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg;build/*.nupkg;!build/*symbols.nupkg'
    publishVstsFeed: 'a0302836-2c67-4470-bcb5-10149e5447f9'
    allowPackageConflicts: true
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
